---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aws-vpce-operator
  namespace: openshift-aws-vpce-operator
rules:
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
  - apiGroups:
      - hypershift.openshift.io
    resources:
      - awsendpointservices
      - hostedcontrolplanes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - config.openshift.io
    resources:
    - infrastructures
    - dnses
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - aws.managed.openshift.io
    resources:
    - accounts
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - avo.openshift.io
    resources:
    - vpcendpoints
    - vpcendpointacceptances
    - vpcendpointtemplates
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
      - avo.openshift.io
    resources:
      - vpcendpoints/status
      - vpcendpointacceptances/status
      - vpcendpointtemplates/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - avo.openshift.io
    resources:
      - vpcendpoints/finalizers
      - vpcendpointacceptances/finalizers
      - vpcendpointtemplates/finalizers
    verbs:
      - update
  - apiGroups:
    - ""
    resources:
    - services
    - services/finalizers
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
